import type {
  ActivityLogAction,
  ActivityLogCategory,
  ActivityLogVisibility,
} from "@prisma/client";

export type ClientActivityField = {
  fieldName: string;
  title: string;
  description: string;
  category: ActivityLogCategory;
  visibility: ActivityLogVisibility;
  action: ActivityLogAction;
};

export const CLIENT_ACTIVITY_FIELDS: ClientActivityField[] = [
  {
    fieldName: "client_type",
    title: "Tipo de cliente actualizado",
    description: "Se actualizó el tipo de cliente.",
    category: "CLIENT",
    visibility: "PUBLIC_INTERNAL",
    action: "UPDATED",
  },
  {
    fieldName: "compliance_profile",
    title: "Perfil de cumplimiento actualizado",
    description: "Se actualizó el perfil de cumplimiento del cliente.",
    category: "CLIENT",
    visibility: "PUBLIC_INTERNAL",
    action: "UPDATED",
  },
  {
    fieldName: "display_name",
    title: "Nombre visible actualizado",
    description: "Se actualizó el nombre visible del cliente.",
    category: "CLIENT",
    visibility: "PUBLIC_INTERNAL",
    action: "UPDATED",
  },
  {
    fieldName: "legal_name",
    title: "Nombre legal actualizado",
    description: "Se actualizó el nombre legal del cliente.",
    category: "CLIENT",
    visibility: "PUBLIC_INTERNAL",
    action: "UPDATED",
  },
  {
    fieldName: "company_name",
    title: "Nombre de empresa actualizado",
    description: "Se actualizó el nombre de empresa del cliente.",
    category: "CLIENT",
    visibility: "PUBLIC_INTERNAL",
    action: "UPDATED",
  },
  {
    fieldName: "commercial_name",
    title: "Nombre comercial actualizado",
    description: "Se actualizó el nombre comercial del cliente.",
    category: "CLIENT",
    visibility: "PUBLIC_INTERNAL",
    action: "UPDATED",
  },
  {
    fieldName: "main_contact_name",
    title: "Contacto principal actualizado",
    description: "Se actualizó el contacto principal del cliente.",
    category: "CLIENT",
    visibility: "PUBLIC_INTERNAL",
    action: "UPDATED",
  },
  {
    fieldName: "identification_country",
    title: "País de identificación actualizado",
    description: "Se actualizó el país de identificación del cliente.",
    category: "CLIENT",
    visibility: "PUBLIC_INTERNAL",
    action: "UPDATED",
  },
  {
    fieldName: "identification_type",
    title: "Tipo de identificación actualizado",
    description: "Se actualizó el tipo de identificación del cliente.",
    category: "CLIENT",
    visibility: "PUBLIC_INTERNAL",
    action: "UPDATED",
  },
  {
    fieldName: "identification_number",
    title: "Número de identificación actualizado",
    description: "Se actualizó el número de identificación del cliente.",
    category: "CLIENT",
    visibility: "PUBLIC_INTERNAL",
    action: "UPDATED",
  },
  {
    fieldName: "first_name",
    title: "Nombre actualizado",
    description: "Se actualizó el nombre del cliente.",
    category: "CLIENT",
    visibility: "PUBLIC_INTERNAL",
    action: "UPDATED",
  },
  {
    fieldName: "last_name_1",
    title: "Primer apellido actualizado",
    description: "Se actualizó el primer apellido del cliente.",
    category: "CLIENT",
    visibility: "PUBLIC_INTERNAL",
    action: "UPDATED",
  },
  {
    fieldName: "last_name_2",
    title: "Segundo apellido actualizado",
    description: "Se actualizó el segundo apellido del cliente.",
    category: "CLIENT",
    visibility: "PUBLIC_INTERNAL",
    action: "UPDATED",
  },
  {
    fieldName: "phone_primary",
    title: "Teléfono principal actualizado",
    description: "Se actualizó el teléfono principal del cliente.",
    category: "CLIENT",
    visibility: "PUBLIC_INTERNAL",
    action: "UPDATED",
  },
  {
    fieldName: "phone_secondary",
    title: "Teléfono secundario actualizado",
    description: "Se actualizó el teléfono secundario del cliente.",
    category: "CLIENT",
    visibility: "PUBLIC_INTERNAL",
    action: "UPDATED",
  },
  {
    fieldName: "email",
    title: "Correo electrónico actualizado",
    description: "Se actualizó el correo electrónico del cliente.",
    category: "CLIENT",
    visibility: "PUBLIC_INTERNAL",
    action: "UPDATED",
  },
  {
    fieldName: "country_code",
    title: "País actualizado",
    description: "Se actualizó el país del cliente.",
    category: "CLIENT",
    visibility: "PUBLIC_INTERNAL",
    action: "UPDATED",
  },
  {
    fieldName: "admin_level_1",
    title: "Provincia actualizada",
    description: "Se actualizó la provincia del cliente.",
    category: "CLIENT",
    visibility: "PUBLIC_INTERNAL",
    action: "UPDATED",
  },
  {
    fieldName: "admin_level_2",
    title: "Cantón actualizado",
    description: "Se actualizó el cantón del cliente.",
    category: "CLIENT",
    visibility: "PUBLIC_INTERNAL",
    action: "UPDATED",
  },
  {
    fieldName: "admin_level_3",
    title: "Distrito actualizado",
    description: "Se actualizó el distrito del cliente.",
    category: "CLIENT",
    visibility: "PUBLIC_INTERNAL",
    action: "UPDATED",
  },
  {
    fieldName: "address_line",
    title: "Dirección actualizada",
    description: "Se actualizó la dirección del cliente.",
    category: "CLIENT",
    visibility: "PUBLIC_INTERNAL",
    action: "UPDATED",
  },
  {
    fieldName: "reference_point",
    title: "Punto de referencia actualizado",
    description: "Se actualizó el punto de referencia del cliente.",
    category: "CLIENT",
    visibility: "PUBLIC_INTERNAL",
    action: "UPDATED",
  },
  {
    fieldName: "location_notes",
    title: "Notas de ubicación actualizadas",
    description: "Se actualizaron las notas de ubicación del cliente.",
    category: "CLIENT",
    visibility: "PUBLIC_INTERNAL",
    action: "UPDATED",
  },
  {
    fieldName: "zone",
    title: "Zona actualizada",
    description: "Se actualizó la zona del cliente.",
    category: "CLIENT",
    visibility: "PUBLIC_INTERNAL",
    action: "UPDATED",
  },
  {
    fieldName: "latitude",
    title: "Latitud actualizada",
    description: "Se actualizó la latitud del cliente.",
    category: "CLIENT",
    visibility: "PUBLIC_INTERNAL",
    action: "UPDATED",
  },
  {
    fieldName: "longitude",
    title: "Longitud actualizada",
    description: "Se actualizó la longitud del cliente.",
    category: "CLIENT",
    visibility: "PUBLIC_INTERNAL",
    action: "UPDATED",
  },
  {
    fieldName: "client_status",
    title: "Estado del cliente actualizado",
    description: "Se actualizó el estado del cliente.",
    category: "CLIENT",
    visibility: "PUBLIC_INTERNAL",
    action: "STATUS_CHANGED",
  },
  {
    fieldName: "whatsapp_opt_in",
    title: "Preferencia de WhatsApp actualizada",
    description: "Se actualizó la preferencia de contacto por WhatsApp.",
    category: "CONTACT",
    visibility: "PUBLIC_INTERNAL",
    action: "UPDATED",
  },
  {
    fieldName: "whatsapp_opt_in_at",
    title: "Fecha de autorización de WhatsApp actualizada",
    description:
      "Se actualizó la fecha de autorización de contacto por WhatsApp.",
    category: "CONTACT",
    visibility: "PUBLIC_INTERNAL",
    action: "UPDATED",
  },
  {
    fieldName: "default_payment_term",
    title: "Condición de pago actualizada",
    description: "Se actualizó la condición de pago del cliente.",
    category: "FINANCE",
    visibility: "FINANCE_ONLY",
    action: "UPDATED",
  },
  {
    fieldName: "default_credit_days",
    title: "Días de crédito actualizados",
    description: "Se actualizaron los días de crédito del cliente.",
    category: "FINANCE",
    visibility: "FINANCE_ONLY",
    action: "UPDATED",
  },
  {
    fieldName: "default_discount_rate",
    title: "Descuento predeterminado actualizado",
    description: "Se actualizó el descuento predeterminado del cliente.",
    category: "FINANCE",
    visibility: "FINANCE_ONLY",
    action: "UPDATED",
  },
  {
    fieldName: "billing_same_as_client",
    title: "Configuración de facturación actualizada",
    description:
      "Se actualizó la configuración para usar los mismos datos del cliente en facturación.",
    category: "FINANCE",
    visibility: "FINANCE_ONLY",
    action: "UPDATED",
  },
  {
    fieldName: "billing_name",
    title: "Nombre de facturación actualizado",
    description: "Se actualizó el nombre de facturación del cliente.",
    category: "FINANCE",
    visibility: "FINANCE_ONLY",
    action: "UPDATED",
  },
  {
    fieldName: "billing_email",
    title: "Correo de facturación actualizado",
    description: "Se actualizó el correo de facturación del cliente.",
    category: "FINANCE",
    visibility: "FINANCE_ONLY",
    action: "UPDATED",
  },
  {
    fieldName: "billing_phone",
    title: "Teléfono de facturación actualizado",
    description: "Se actualizó el teléfono de facturación del cliente.",
    category: "FINANCE",
    visibility: "FINANCE_ONLY",
    action: "UPDATED",
  },
  {
    fieldName: "billing_address",
    title: "Dirección de facturación actualizada",
    description: "Se actualizó la dirección de facturación del cliente.",
    category: "FINANCE",
    visibility: "FINANCE_ONLY",
    action: "UPDATED",
  },
  {
    fieldName: "tax_id",
    title: "Identificación tributaria actualizada",
    description: "Se actualizó la identificación tributaria del cliente.",
    category: "FINANCE",
    visibility: "FINANCE_ONLY",
    action: "UPDATED",
  },
  {
    fieldName: "tax_exempt",
    title: "Exoneración actualizada",
    description: "Se actualizó la configuración de exoneración del cliente.",
    category: "FINANCE",
    visibility: "FINANCE_ONLY",
    action: "UPDATED",
  },
  {
    fieldName: "preferred_currency",
    title: "Moneda preferida actualizada",
    description: "Se actualizó la moneda preferida del cliente.",
    category: "FINANCE",
    visibility: "FINANCE_ONLY",
    action: "UPDATED",
  },
  {
    fieldName: "credit_limit",
    title: "Límite de crédito actualizado",
    description: "Se actualizó el límite de crédito del cliente.",
    category: "FINANCE",
    visibility: "FINANCE_ONLY",
    action: "UPDATED",
  },
  {
    fieldName: "data_consent_at",
    title: "Consentimiento de datos actualizado",
    description:
      "Se actualizó la fecha de consentimiento para tratamiento de datos.",
    category: "SYSTEM",
    visibility: "ADMIN_ONLY",
    action: "UPDATED",
  },
  {
    fieldName: "data_consent_source",
    title: "Origen del consentimiento actualizado",
    description:
      "Se actualizó el origen del consentimiento para tratamiento de datos.",
    category: "SYSTEM",
    visibility: "ADMIN_ONLY",
    action: "UPDATED",
  },
];
