export const CLIENT_SOURCE = {
  key: "clients",
  label: "Clientes",
  description: "Clientes registrados, contacto, ubicación, actividad y saldos.",
  endpoint: "/api/reports/builder/clients",
  metadataEndpoint: "/api/reports/builder/metadata",
  emptyMessage: "No hay clientes para mostrar con los filtros actuales.",
  exportTitle: "CLARIUS - Reporte de clientes",
  excelFileName: "reporte-clientes.xlsx",
  pdfFileName: "reporte-clientes.pdf",

  defaultColumns: [
    "client_name",
    "phone_primary",
    "email",
    "client_status",
    "whatsapp_opt_in",
    "admin_level_1",
    "admin_level_2",
    "installations_count",
    "pending_billing",
  ],

  columns: [
    {
      key: "client_id",
      label: "ID cliente",
      description: "Identificador interno del cliente.",
      group: "Sistema",
    },
    {
      key: "client_name",
      label: "Cliente",
      description: "Nombre comercial, empresa o persona.",
      group: "Cliente",
    },
    {
      key: "client_type",
      label: "Tipo",
      description: "Persona, empresa u otro tipo de cliente.",
      group: "Cliente",
    },
    {
      key: "phone_primary",
      label: "Teléfono principal",
      description: "Número principal de contacto.",
      group: "Contacto",
    },
    {
      key: "phone_secondary",
      label: "Teléfono secundario",
      description: "Número alternativo de contacto.",
      group: "Contacto",
    },
    {
      key: "email",
      label: "Email",
      description: "Correo electrónico principal.",
      group: "Contacto",
    },
    {
      key: "client_status",
      label: "Estado",
      description: "Estado comercial u operativo del cliente.",
      group: "Cliente",
    },
    {
      key: "whatsapp_opt_in",
      label: "WhatsApp",
      description: "Indica si acepta contacto por WhatsApp.",
      group: "Contacto",
    },
    {
      key: "auto_contact_enabled",
      label: "Contacto automático",
      description: "Indica si permite flujos automáticos.",
      group: "Contacto",
    },
    {
      key: "country_code",
      label: "País",
      description: "Código de país.",
      group: "Ubicación",
    },
    {
      key: "admin_level_1",
      label: "Provincia / Nivel 1",
      description: "Primera división administrativa.",
      group: "Ubicación",
    },
    {
      key: "admin_level_2",
      label: "Cantón / Nivel 2",
      description: "Segunda división administrativa.",
      group: "Ubicación",
    },
    {
      key: "admin_level_3",
      label: "Distrito / Nivel 3",
      description: "Tercera división administrativa.",
      group: "Ubicación",
    },
    {
      key: "city",
      label: "Ciudad",
      description: "Ciudad o localidad.",
      group: "Ubicación",
    },
    {
      key: "zone",
      label: "Zona",
      description: "Zona textual asignada al cliente.",
      group: "Ubicación",
    },
    {
      key: "address_line",
      label: "Dirección",
      description: "Dirección principal.",
      group: "Ubicación",
    },
    {
      key: "operational_zone",
      label: "Zona operativa",
      description: "Zona operativa asociada.",
      group: "Operación",
    },
    {
      key: "installations_count",
      label: "Instalaciones",
      description: "Cantidad de instalaciones asociadas.",
      group: "Actividad",
    },
    {
      key: "follow_ups_count",
      label: "Mantenimientos",
      description: "Cantidad de mantenimientos asociados.",
      group: "Actividad",
    },
    {
      key: "contact_attempts_count",
      label: "Intentos de contacto",
      description: "Cantidad de intentos de contacto registrados.",
      group: "Actividad",
    },
    {
      key: "invoices_count",
      label: "Facturas",
      description: "Cantidad de facturas asociadas.",
      group: "Finanzas",
    },
    {
      key: "pending_billing",
      label: "Saldo pendiente",
      description: "Monto pendiente de facturación o cobro.",
      group: "Finanzas",
    },
    {
      key: "default_payment_term",
      label: "Condición de pago",
      description: "Condición de pago por defecto.",
      group: "Finanzas",
    },
    {
      key: "preferred_currency",
      label: "Moneda",
      description: "Moneda preferida del cliente.",
      group: "Finanzas",
    },
    {
      key: "tax_exempt",
      label: "Exento",
      description: "Indica si el cliente está marcado como exento.",
      group: "Finanzas",
    },
    {
      key: "created_at",
      label: "Creado",
      description: "Fecha de creación.",
      group: "Sistema",
    },
    {
      key: "updated_at",
      label: "Actualizado",
      description: "Fecha de última actualización.",
      group: "Sistema",
    },
  ],
} as const;
