export const FOLLOW_UP_SOURCE = {
  key: "follow-ups",
  label: "Mantenimientos",
  description:
    "Mantenimientos, fechas, estados, técnicos, contacto y facturación.",
  endpoint: "/api/reports/builder/follow-ups",
  metadataEndpoint: "/api/reports/builder/follow-ups/metadata",
  emptyMessage: "No hay mantenimientos para mostrar con los filtros actuales.",
  exportTitle: "CLARIUS - Reporte de mantenimientos",
  excelFileName: "reporte-mantenimientos.xlsx",
  pdfFileName: "reporte-mantenimientos.pdf",

  defaultColumns: [
    "client_name",
    "installation_reference",
    "follow_up_status",
    "target_date",
    "due_date",
    "scheduled_date",
    "is_completed",
    "technician_name",
    "pending_billing",
  ],

  columns: [
    {
      key: "follow_up_id",
      label: "ID mantenimiento",
      description: "Identificador interno del mantenimiento.",
      group: "Sistema",
    },
    {
      key: "client_name",
      label: "Cliente",
      description: "Cliente asociado al mantenimiento.",
      group: "Cliente",
    },
    {
      key: "installation_reference",
      label: "Instalación",
      description: "Referencia de la instalación asociada.",
      group: "Instalación",
    },
    {
      key: "installation_service_type",
      label: "Tipo de servicio",
      description: "Tipo de servicio de la instalación.",
      group: "Instalación",
    },
    {
      key: "follow_up_status",
      label: "Estado",
      description: "Estado del mantenimiento.",
      group: "Mantenimiento",
    },
    {
      key: "target_date",
      label: "Fecha objetivo",
      description: "Fecha objetivo del mantenimiento.",
      group: "Fechas",
    },
    {
      key: "due_date",
      label: "Fecha vencimiento",
      description: "Fecha límite del mantenimiento.",
      group: "Fechas",
    },
    {
      key: "scheduled_date",
      label: "Fecha programada",
      description: "Fecha programada para realizar el mantenimiento.",
      group: "Fechas",
    },
    {
      key: "completed_at",
      label: "Fecha completado",
      description: "Fecha en que se completó el mantenimiento.",
      group: "Fechas",
    },
    {
      key: "is_completed",
      label: "Completado",
      description: "Indica si el mantenimiento está completado.",
      group: "Mantenimiento",
    },
    {
      key: "priority",
      label: "Prioridad",
      description: "Prioridad asignada.",
      group: "Mantenimiento",
    },
    {
      key: "maintenance_type",
      label: "Tipo mantenimiento",
      description: "Tipo de mantenimiento registrado.",
      group: "Mantenimiento",
    },
    {
      key: "technician_name",
      label: "Técnico",
      description: "Técnico asignado.",
      group: "Operación",
    },
    {
      key: "created_from",
      label: "Origen",
      description: "Origen del mantenimiento.",
      group: "Sistema",
    },
    {
      key: "billing_status",
      label: "Estado facturación",
      description: "Estado de facturación del mantenimiento.",
      group: "Finanzas",
    },
    {
      key: "estimated_amount",
      label: "Monto estimado",
      description: "Monto estimado.",
      group: "Finanzas",
    },
    {
      key: "final_amount",
      label: "Monto final",
      description: "Monto final.",
      group: "Finanzas",
    },
    {
      key: "cost_amount",
      label: "Costo",
      description: "Costo asociado.",
      group: "Finanzas",
    },
    {
      key: "pending_billing",
      label: "Saldo pendiente",
      description: "Saldo pendiente asociado.",
      group: "Finanzas",
    },
    {
      key: "contact_attempts_count",
      label: "Intentos contacto",
      description: "Cantidad de intentos de contacto.",
      group: "Contacto",
    },
    {
      key: "contact_flows_count",
      label: "Flujos contacto",
      description: "Cantidad de flujos de contacto.",
      group: "Contacto",
    },
    {
      key: "follow_up_notes_count",
      label: "Notas",
      description: "Cantidad de notas asociadas.",
      group: "Actividad",
    },
    {
      key: "invoices_count",
      label: "Facturas",
      description: "Cantidad de facturas asociadas.",
      group: "Finanzas",
    },
    {
      key: "operational_zone",
      label: "Zona operativa",
      description: "Zona operativa asociada.",
      group: "Operación",
    },
    {
      key: "reason",
      label: "Razón",
      description: "Motivo del mantenimiento.",
      group: "Detalle",
    },
    {
      key: "notes",
      label: "Notas",
      description: "Notas generales.",
      group: "Detalle",
    },
    {
      key: "billing_notes",
      label: "Notas facturación",
      description: "Notas relacionadas con facturación.",
      group: "Finanzas",
    },
    {
      key: "billing_block_reason",
      label: "Bloqueo facturación",
      description: "Razón de bloqueo de facturación.",
      group: "Finanzas",
    },
    {
      key: "created_at",
      label: "Creado",
      description: "Fecha de creación.",
      group: "Sistema",
    },
    {
      key: "updated_at",
      label: "Actualizado",
      description: "Fecha de última actualización.",
      group: "Sistema",
    },
  ],
} as const;
