export const INSTALLATION_SOURCE = {
  key: "installations",
  label: "Instalaciones",
  description:
    "Instalaciones, servicios, técnicos, ubicación, estados y facturación.",
  endpoint: "/api/reports/builder/installations",
  metadataEndpoint: "/api/reports/builder/installations/metadata",
  emptyMessage: "No hay instalaciones para mostrar con los filtros actuales.",
  exportTitle: "CLARIUS - Reporte de instalaciones",
  excelFileName: "reporte-instalaciones.xlsx",
  pdfFileName: "reporte-instalaciones.pdf",

  defaultColumns: [
    "client_name",
    "service_type",
    "installation_date",
    "installation_status",
    "billing_status",
    "technician_name",
    "admin_level_1",
    "admin_level_2",
    "pending_billing",
  ],

  columns: [
    {
      key: "installation_id",
      label: "ID instalación",
      description: "Identificador interno de la instalación.",
      group: "Sistema",
    },
    {
      key: "client_name",
      label: "Cliente",
      description: "Cliente asociado a la instalación.",
      group: "Cliente",
    },
    {
      key: "service_type",
      label: "Tipo de servicio",
      description: "Servicio asociado a la instalación.",
      group: "Instalación",
    },
    {
      key: "installation_date",
      label: "Fecha instalación",
      description: "Fecha registrada para la instalación.",
      group: "Instalación",
    },
    {
      key: "installation_status",
      label: "Estado instalación",
      description: "Estado operativo de la instalación.",
      group: "Instalación",
    },
    {
      key: "is_active",
      label: "Activa",
      description: "Indica si la instalación está activa.",
      group: "Instalación",
    },
    {
      key: "billing_status",
      label: "Estado facturación",
      description: "Estado financiero o de facturación.",
      group: "Finanzas",
    },
    {
      key: "estimated_amount",
      label: "Monto estimado",
      description: "Monto estimado del trabajo.",
      group: "Finanzas",
    },
    {
      key: "final_amount",
      label: "Monto final",
      description: "Monto final registrado.",
      group: "Finanzas",
    },
    {
      key: "cost_amount",
      label: "Costo",
      description: "Costo asociado al trabajo.",
      group: "Finanzas",
    },
    {
      key: "pending_billing",
      label: "Saldo pendiente",
      description: "Monto pendiente asociado.",
      group: "Finanzas",
    },
    {
      key: "warranty_months",
      label: "Garantía meses",
      description: "Cantidad de meses de garantía.",
      group: "Garantía",
    },
    {
      key: "warranty_end_date",
      label: "Fin garantía",
      description: "Fecha de finalización de garantía.",
      group: "Garantía",
    },
    {
      key: "technician_name",
      label: "Técnico",
      description: "Técnico asignado.",
      group: "Operación",
    },
    {
      key: "address_line",
      label: "Dirección",
      description: "Dirección de la instalación.",
      group: "Ubicación",
    },
    {
      key: "city",
      label: "Ciudad",
      description: "Ciudad o localidad.",
      group: "Ubicación",
    },
    {
      key: "admin_level_1",
      label: "Provincia / Nivel 1",
      description: "Primera división administrativa.",
      group: "Ubicación",
    },
    {
      key: "admin_level_2",
      label: "Cantón / Nivel 2",
      description: "Segunda división administrativa.",
      group: "Ubicación",
    },
    {
      key: "admin_level_3",
      label: "Distrito / Nivel 3",
      description: "Tercera división administrativa.",
      group: "Ubicación",
    },
    {
      key: "zone",
      label: "Zona",
      description: "Zona textual registrada.",
      group: "Ubicación",
    },
    {
      key: "operational_zone",
      label: "Zona operativa",
      description: "Zona operativa asociada.",
      group: "Operación",
    },
    {
      key: "components_count",
      label: "Componentes",
      description: "Cantidad de componentes asociados.",
      group: "Actividad",
    },
    {
      key: "follow_ups_count",
      label: "Mantenimientos",
      description: "Cantidad de mantenimientos asociados.",
      group: "Actividad",
    },
    {
      key: "pending_follow_up_date",
      label: "Próximo mantenimiento",
      description: "Fecha de mantenimiento pendiente.",
      group: "Actividad",
    },
    {
      key: "invoices_count",
      label: "Facturas",
      description: "Cantidad de facturas asociadas.",
      group: "Finanzas",
    },
    {
      key: "description",
      label: "Descripción",
      description: "Descripción general de la instalación.",
      group: "Detalle",
    },
    {
      key: "technical_observations",
      label: "Observaciones técnicas",
      description: "Notas técnicas registradas.",
      group: "Detalle",
    },
    {
      key: "reference_point",
      label: "Punto de referencia",
      description: "Referencia de ubicación.",
      group: "Ubicación",
    },
    {
      key: "location_notes",
      label: "Notas ubicación",
      description: "Notas adicionales de ubicación.",
      group: "Ubicación",
    },
    {
      key: "created_at",
      label: "Creado",
      description: "Fecha de creación.",
      group: "Sistema",
    },
    {
      key: "updated_at",
      label: "Actualizado",
      description: "Fecha de última actualización.",
      group: "Sistema",
    },
  ],
} as const;
