import type { CountryPreset } from "./index";

export const LATIN_AMERICA_COUNTRY_PRESETS: Record<string, CountryPreset> = {
  CR: {
    countryCode: "CR",
    countryName: "Costa Rica",
    primaryCurrency: "CRC",
    secondaryCurrency: "USD",
    defaultTimezone: "America/Costa_Rica",
    timezones: [{ value: "America/Costa_Rica", label: "Costa Rica Time" }],
    phonePrefix: "+506",
    defaultTaxRate: 13,
    adminLevel1Label: "Provincia",
    adminLevel2Label: "Cantón",
    adminLevel3Label: "Distrito",
    dateFormat: "DD/MM/YYYY",
  },

  PA: {
    countryCode: "PA",
    countryName: "Panamá",
    primaryCurrency: "USD",
    secondaryCurrency: null,
    defaultTimezone: "America/Panama",
    timezones: [{ value: "America/Panama", label: "Panama Time" }],
    phonePrefix: "+507",
    defaultTaxRate: 7,
    adminLevel1Label: "Provincia / Comarca",
    adminLevel2Label: "Distrito",
    adminLevel3Label: "Corregimiento",
    dateFormat: "DD/MM/YYYY",
  },

  MX: {
    countryCode: "MX",
    countryName: "México",
    primaryCurrency: "MXN",
    secondaryCurrency: "USD",
    defaultTimezone: "America/Mexico_City",
    timezones: [
      { value: "America/Cancun", label: "Eastern Time - Quintana Roo" },
      { value: "America/Mexico_City", label: "Central Time" },
      { value: "America/Monterrey", label: "Central Time - Monterrey" },
      { value: "America/Mazatlan", label: "Mountain Time" },
      { value: "America/Chihuahua", label: "Mountain Time - Chihuahua" },
      { value: "America/Hermosillo", label: "Mountain Time - Sonora" },
      { value: "America/Tijuana", label: "Pacific Time - Baja California" },
    ],
    phonePrefix: "+52",
    defaultTaxRate: 16,
    adminLevel1Label: "Estado / Ciudad de México",
    adminLevel2Label: "Municipio / Alcaldía",
    adminLevel3Label: "Colonia / Localidad",
    dateFormat: "DD/MM/YYYY",
  },

  CO: {
    countryCode: "CO",
    countryName: "Colombia",
    primaryCurrency: "COP",
    secondaryCurrency: "USD",
    defaultTimezone: "America/Bogota",
    timezones: [{ value: "America/Bogota", label: "Colombia Time" }],
    phonePrefix: "+57",
    defaultTaxRate: 19,
    adminLevel1Label: "Departamento / Distrito Capital",
    adminLevel2Label: "Municipio",
    adminLevel3Label: "Barrio / Localidad",
    dateFormat: "DD/MM/YYYY",
  },

  GT: {
    countryCode: "GT",
    countryName: "Guatemala",
    primaryCurrency: "GTQ",
    secondaryCurrency: "USD",
    defaultTimezone: "America/Guatemala",
    timezones: [{ value: "America/Guatemala", label: "Guatemala Time" }],
    phonePrefix: "+502",
    defaultTaxRate: 12,
    adminLevel1Label: "Departamento",
    adminLevel2Label: "Municipio",
    adminLevel3Label: "Zona / Aldea / Caserío",
    dateFormat: "DD/MM/YYYY",
  },

  SV: {
    countryCode: "SV",
    countryName: "El Salvador",
    primaryCurrency: "USD",
    secondaryCurrency: null,
    defaultTimezone: "America/El_Salvador",
    timezones: [{ value: "America/El_Salvador", label: "El Salvador Time" }],
    phonePrefix: "+503",
    defaultTaxRate: 13,
    adminLevel1Label: "Departamento",
    adminLevel2Label: "Municipio",
    adminLevel3Label: "Distrito / Cantón",
    dateFormat: "DD/MM/YYYY",
  },

  HN: {
    countryCode: "HN",
    countryName: "Honduras",
    primaryCurrency: "HNL",
    secondaryCurrency: "USD",
    defaultTimezone: "America/Tegucigalpa",
    timezones: [{ value: "America/Tegucigalpa", label: "Honduras Time" }],
    phonePrefix: "+504",
    defaultTaxRate: 15,
    adminLevel1Label: "Departamento",
    adminLevel2Label: "Municipio",
    adminLevel3Label: "Aldea / Caserío / Barrio",
    dateFormat: "DD/MM/YYYY",
  },

  NI: {
    countryCode: "NI",
    countryName: "Nicaragua",
    primaryCurrency: "NIO",
    secondaryCurrency: "USD",
    defaultTimezone: "America/Managua",
    timezones: [{ value: "America/Managua", label: "Nicaragua Time" }],
    phonePrefix: "+505",
    defaultTaxRate: 15,
    adminLevel1Label: "Departamento / Región Autónoma",
    adminLevel2Label: "Municipio",
    adminLevel3Label: "Barrio / Comunidad",
    dateFormat: "DD/MM/YYYY",
  },

  DO: {
    countryCode: "DO",
    countryName: "República Dominicana",
    primaryCurrency: "DOP",
    secondaryCurrency: "USD",
    defaultTimezone: "America/Santo_Domingo",
    timezones: [
      { value: "America/Santo_Domingo", label: "Dominican Republic Time" },
    ],
    phonePrefix: "+1",
    defaultTaxRate: 18,
    adminLevel1Label: "Provincia / Distrito Nacional",
    adminLevel2Label: "Municipio",
    adminLevel3Label: "Distrito municipal / Sector",
    dateFormat: "DD/MM/YYYY",
  },

  PR: {
    countryCode: "PR",
    countryName: "Puerto Rico",
    primaryCurrency: "USD",
    secondaryCurrency: null,
    defaultTimezone: "America/Puerto_Rico",
    timezones: [{ value: "America/Puerto_Rico", label: "Puerto Rico Time" }],
    phonePrefix: "+1",
    defaultTaxRate: 11.5,
    adminLevel1Label: "Municipio",
    adminLevel2Label: "Barrio",
    adminLevel3Label: "Sector / Urbanización",
    dateFormat: "MM/DD/YYYY",
  },

  AR: {
    countryCode: "AR",
    countryName: "Argentina",
    primaryCurrency: "ARS",
    secondaryCurrency: "USD",
    defaultTimezone: "America/Argentina/Buenos_Aires",
    timezones: [
      { value: "America/Argentina/Buenos_Aires", label: "Argentina Time" },
    ],
    phonePrefix: "+54",
    defaultTaxRate: 21,
    adminLevel1Label: "Provincia / Ciudad Autónoma",
    adminLevel2Label: "Departamento / Partido / Comuna",
    adminLevel3Label: "Localidad / Barrio",
    dateFormat: "DD/MM/YYYY",
  },

  CL: {
    countryCode: "CL",
    countryName: "Chile",
    primaryCurrency: "CLP",
    secondaryCurrency: "USD",
    defaultTimezone: "America/Santiago",
    timezones: [
      { value: "America/Santiago", label: "Mainland Chile Time" },
      { value: "Pacific/Easter", label: "Easter Island Time" },
    ],
    phonePrefix: "+56",
    defaultTaxRate: 19,
    adminLevel1Label: "Región",
    adminLevel2Label: "Provincia",
    adminLevel3Label: "Comuna",
    dateFormat: "DD/MM/YYYY",
  },

  PE: {
    countryCode: "PE",
    countryName: "Perú",
    primaryCurrency: "PEN",
    secondaryCurrency: "USD",
    defaultTimezone: "America/Lima",
    timezones: [{ value: "America/Lima", label: "Peru Time" }],
    phonePrefix: "+51",
    defaultTaxRate: 18,
    adminLevel1Label: "Departamento / Región",
    adminLevel2Label: "Provincia",
    adminLevel3Label: "Distrito",
    dateFormat: "DD/MM/YYYY",
  },

  EC: {
    countryCode: "EC",
    countryName: "Ecuador",
    primaryCurrency: "USD",
    secondaryCurrency: null,
    defaultTimezone: "America/Guayaquil",
    timezones: [
      { value: "America/Guayaquil", label: "Mainland Ecuador Time" },
      { value: "Pacific/Galapagos", label: "Galapagos Time" },
    ],
    phonePrefix: "+593",
    defaultTaxRate: 15,
    adminLevel1Label: "Provincia",
    adminLevel2Label: "Cantón",
    adminLevel3Label: "Parroquia",
    dateFormat: "DD/MM/YYYY",
  },

  BO: {
    countryCode: "BO",
    countryName: "Bolivia",
    primaryCurrency: "BOB",
    secondaryCurrency: "USD",
    defaultTimezone: "America/La_Paz",
    timezones: [{ value: "America/La_Paz", label: "Bolivia Time" }],
    phonePrefix: "+591",
    defaultTaxRate: 13,
    adminLevel1Label: "Departamento",
    adminLevel2Label: "Provincia",
    adminLevel3Label: "Municipio / Localidad",
    dateFormat: "DD/MM/YYYY",
  },

  PY: {
    countryCode: "PY",
    countryName: "Paraguay",
    primaryCurrency: "PYG",
    secondaryCurrency: "USD",
    defaultTimezone: "America/Asuncion",
    timezones: [{ value: "America/Asuncion", label: "Paraguay Time" }],
    phonePrefix: "+595",
    defaultTaxRate: 10,
    adminLevel1Label: "Departamento / Capital",
    adminLevel2Label: "Distrito",
    adminLevel3Label: "Barrio / Compañía",
    dateFormat: "DD/MM/YYYY",
  },

  UY: {
    countryCode: "UY",
    countryName: "Uruguay",
    primaryCurrency: "UYU",
    secondaryCurrency: "USD",
    defaultTimezone: "America/Montevideo",
    timezones: [{ value: "America/Montevideo", label: "Uruguay Time" }],
    phonePrefix: "+598",
    defaultTaxRate: 22,
    adminLevel1Label: "Departamento",
    adminLevel2Label: "Municipio / Localidad",
    adminLevel3Label: "Barrio / Zona",
    dateFormat: "DD/MM/YYYY",
  },

  VE: {
    countryCode: "VE",
    countryName: "Venezuela",
    primaryCurrency: "VES",
    secondaryCurrency: "USD",
    defaultTimezone: "America/Caracas",
    timezones: [{ value: "America/Caracas", label: "Venezuela Time" }],
    phonePrefix: "+58",
    defaultTaxRate: 16,
    adminLevel1Label: "Estado / Distrito Capital",
    adminLevel2Label: "Municipio",
    adminLevel3Label: "Parroquia",
    dateFormat: "DD/MM/YYYY",
  },

  BR: {
    countryCode: "BR",
    countryName: "Brasil",
    primaryCurrency: "BRL",
    secondaryCurrency: "USD",
    defaultTimezone: "America/Sao_Paulo",
    timezones: [
      { value: "America/Noronha", label: "Fernando de Noronha Time" },
      { value: "America/Sao_Paulo", label: "Brasilia Time" },
      { value: "America/Cuiaba", label: "Amazon Time - Mato Grosso" },
      { value: "America/Manaus", label: "Amazon Time" },
      { value: "America/Rio_Branco", label: "Acre Time" },
    ],
    phonePrefix: "+55",
    defaultTaxRate: 0,
    adminLevel1Label: "Estado",
    adminLevel2Label: "Municipio",
    adminLevel3Label: "Barrio / Distrito",
    dateFormat: "DD/MM/YYYY",
  },
};
